tabs to spaces please

diff --git a/cvs2git-funcs b/cvs2git-funcs
--- a/cvs2git-funcs
+++ b/cvs2git-funcs
@@ -30,12 +30,12 @@ fetchrepo() {
     mkdir -p $REPOCVS/CVSROOT/Emptydir
 
     case $PROJ in
-	ensembl*) fetchrepo_ensembl ;;
-	anacode) fetchrepo_intcvs1 ;;
-	acedb) fetchrepo_intcvs1 ;;
-	zmap) fetchrepo_intcvs1 ;;
-	*) echo "Fetch $PROJ from which repository?" >&2
-	    exit 9 ;;
+    ensembl*) fetchrepo_ensembl ;;
+    anacode) fetchrepo_intcvs1 ;;
+    acedb) fetchrepo_intcvs1 ;;
+    zmap) fetchrepo_intcvs1 ;;
+    *) echo "Fetch $PROJ from which repository?" >&2
+        exit 9 ;;
     esac
 
     [ -n "$CVS2GIT_SQUIRREL_DIR" ] && squirrel_hwime_cvs
@@ -79,10 +79,10 @@ unpack_hwime() { # here's one I made earlier
     tar xfz $fn
 
     case $fn in
-	*.repo.tgz)
-	    cvsrepo_lockfix
-	    apply_hackery
-	    ;;
+    *.repo.tgz)
+        cvsrepo_lockfix
+        apply_hackery
+        ;;
     esac
 
     return 0
@@ -118,28 +118,28 @@ subdir_promote() {
     topdir=$( cd $REPOCVS; find . -type f -name '*,v' | sed -e 's|^\./||; s|/.*||' | sort -u )
     numdirs=$( echo $topdir | wc -w )
     if [ $numdirs = 1 ]; then
-	echo "All ,v files are under $topdir/ - promote them"
-	mv -v $REPOCVS/$topdir/* $REPOCVS/
+    echo "All ,v files are under $topdir/ - promote them"
+    mv -v $REPOCVS/$topdir/* $REPOCVS/
     if [ -f $REPOCVS/$topdir/.cvsignore,v ]; then
         echo ".cvsignore,v file found under $topdir/ - promote it"
         mv -v $REPOCVS/$topdir/.cvsignore,v $REPOCVS/.
     fi
-	rmdir $REPOCVS/$topdir
+    rmdir $REPOCVS/$topdir
     else
-	echo "Multiple top level directories ($topdir) prevent subdirectory promotion"
+    echo "Multiple top level directories ($topdir) prevent subdirectory promotion"
     fi
 }
 
 apply_hackery() {
     HACKFILE=$GIDIR/$PROJ-hackery.sh
     if [ -f "$HACKFILE" ]; then
-	echo Applying $HACKFILE
-	$HACKFILE $REPOCVS || {
-	    echo Hackery failed >&2
-	    exit 33
-	}
+    echo Applying $HACKFILE
+    $HACKFILE $REPOCVS || {
+        echo Hackery failed >&2
+        exit 33
+    }
     else
-	echo $HACKFILE absent, no worries
+    echo $HACKFILE absent, no worries
     fi
 
     if [ -n "$FETCHREPO_INTERACT" ]; then
@@ -214,10 +214,10 @@ checktag() {
     GITREV=${2:-$CVSREV}
 
     case $CVSREV in
-	unlabeled-*)
-	    echo "$CVSREV: cannot checktag this, fix the CVS repo" > $CHKNAME
-	    diffbad=$[ $diffbad + 1 ]
-	    return 0 ;;
+    unlabeled-*)
+        echo "$CVSREV: cannot checktag this, fix the CVS repo" > $CHKNAME
+        diffbad=$[ $diffbad + 1 ]
+        return 0 ;;
     esac
 
     CVSCO=$C2G_TMP/cvsco
@@ -231,7 +231,7 @@ checktag() {
     git_preresetcheck
 
     if ! git show-ref _diff_to_cvs > /dev/null; then
-	git branch _diff_to_cvs
+    git branch _diff_to_cvs
     fi
     git checkout -q _diff_to_cvs
 
@@ -242,11 +242,11 @@ checktag() {
     # If we have this commit already, there is no point hammering CVS
     # again to diff it.  Short-circuit to OK.
     if [ -f "$KNOWN_GOOD_CILIST" ]; then
-	CIID=$( git log -1 --format=%H )
-	if grep $CIID $KNOWN_GOOD_CILIST > /dev/null; then
-	    echo "  checktag $CVSREV vs $GITREV: $CIID is in $KNOWN_GOOD_CILIST"
-	    return 0
-	fi
+        CIID=$( git log -1 --format=%H )
+        if grep $CIID $KNOWN_GOOD_CILIST > /dev/null; then
+            echo "  checktag $CVSREV vs $GITREV: $CIID is in $KNOWN_GOOD_CILIST"
+            return 0
+        fi
     fi
 
     # Make a fresh CVS checkout
@@ -259,9 +259,9 @@ checktag() {
     # want to check some more after
     cd $GITCO
     if diff -xCVS -x.git -ru $CVSCO $GITCO > $CHKNAME; then
-	diffok=$[ $diffok + 1 ]
+    diffok=$[ $diffok + 1 ]
     else
-	diffbad=$[ $diffbad + 1 ]
+    diffbad=$[ $diffbad + 1 ]
     fi
 }
 
@@ -291,7 +291,7 @@ LST
     cd $C2G_TMP
     checktag HEAD master
     for tag in $refs_tag $refs_branch; do
-	checktag $tag
+    checktag $tag
     done
 }
 
@@ -302,12 +302,12 @@ clean_git_namespace() { # Requires $refs_tag $refs_branch
 
     # Rename all CVS branches & tags down a level
     for ref in $refs_branch; do
-	git branch -m $ref cvs/$ref
+    git branch -m $ref cvs/$ref
     done
     for ref in $refs_tag; do
-	echo -ne "Create tag cvs/$ref; \t"
-	git tag cvs/$ref $ref
-	git tag -d $ref
+    echo -ne "Create tag cvs/$ref; \t"
+    git tag cvs/$ref $ref
+    git tag -d $ref
     done
 
     # Retain master from CVS MAIN
@@ -338,8 +338,8 @@ checktag_show_summary() {
 git_preresetcheck() {
     # Paranoia to avoid another accident.  8-(
     if [ ! -f ".git/c2g-mark" ]; then
-	echo ".git/c2g-mark not found - not my repo?" >&2
-	exit 11
+    echo ".git/c2g-mark not found - not my repo?" >&2
+    exit 11
     fi
 }
 
